set(CMAKE_SYSTEM_NAME FreeBSD)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
get_filename_component(X360_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(SDK "${X360_ROOT}/.deps/PS5_Vulkan/.deps/native/ps5-payload-sdk")
set(CMAKE_C_COMPILER clang-21)
set(CMAKE_CXX_COMPILER clang++-21)
set(CMAKE_C_COMPILER_TARGET x86_64-sie-ps5)
set(CMAKE_CXX_COMPILER_TARGET x86_64-sie-ps5)
set(COMMON "-fvisibility-nodllstorageclass=default -isysroot ${SDK} -isystem ${SDK}/target/include -fno-stack-protector -fno-plt -femulated-tls -fdenormal-fp-math=ieee")
set(CMAKE_C_FLAGS_INIT "${COMMON}")
set(CMAKE_CXX_FLAGS_INIT "-isystem ${SDK}/target/include/c++/v1 ${COMMON} -fexceptions -fcxx-exceptions -frtti")
